@Library('jenkins-shared-library') _ // Global pipeline libraries in the system configuration
def configmap = [
    project: "expense",
    component: "backend"
]

if ( !env.BRANCH_NAME.equalsIgnoreCase('main')) {  //true if the branch is feature branch
    nodeJSEKSPipeline(configmap)
}
else {
    echo "Follow the process of PROD Release"
}