pipeline {
    agent {
        label 'AGENT-1'
    }
    options {
        timeout(time: 30, unit: 'MINUTES')
        disableConcurrentBuilds()
    }
    parameters {
        choice(name: 'ENVIRONMENT', choices: ['dev','qa','uat','pre-prod','prod'], description: 'Select the environment')
        string(name: 'version', description: 'Enter the application version')
        string(name: 'jira-id', description: 'Enter Application Jira account ID')
    }
    environment {
        appVersion = '' //This is global varaiable section can use across pipeline
        region = 'us-east-1'
        account_id = ''
        project = 'expense'
        component = 'backend'
        environment = ''
    }
    stages {
        stage('Setup Environment'){
            steps {
                script {
                    environment = params.ENVIRONMENT
                    appVersion = params.version
                    account_id = pipelineGlobals.getAccountID(environment)
                }
            }
        }

        stage('Integration tests') {
            when {
                expression { params.ENVIRONMENT = 'uat'}
            }
            steps {
                script {
                    sh """
                        echo "Run Integration Tests"
                    """
                }
            }
        }
        stage('Check Jira') {
            when {
                expression { params.ENVIRONMENT = 'prod' }
            }
            steps {
                script {
                    sh """
                        echo "check Jira status"
                        echo "check Jira deployment window'
                        echo "fail pipeline if above two are not true"
                    """
                }
            }
        }
        stage('Deploy') {
            steps {
                withAWS(region: 'us-east-1', credentials: 'aws-creds'){
                    sh """
                        aws eks update-config --region ${region} --name ${project}-dev
                        cd helm
                        sed -i 's/IMAGE_VERSION/${appVersion}/g' values-${environment}.yaml
                        heml upgrade --install ${component} -n ${project} -f values-${environment}.yaml .
                    """
                }
            }
        }
    }
    post {
        always{
            echo "This section runs always"
            deleteDir()
        }
        success {
            echo "This section runs when the pipeline success"
            deleteDir()
        }
        failure {
            echo " This section runs when the pipeline failure"
            deleteDir()
        }
    }
}